name: Prepare for Release
on:
  push:
    branches:
      - release/*

jobs:
  prepare:
    name: Prepare for Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Release Version
        run: echo RELEASE_VERSION=$(echo $GITHUB_REF_NAME | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+.*$') >> $GITHUB_ENV
      - name: Changes Heading Up-To-Date Check
        run: |
          date=$(date "+%Y-%m-%d")
          header=$(head -n1 Changes.md)
          if [ "$header" != "$RELEASE_VERSION  $date" ]; then
              echo "Changes.md is out of date!"
              echo "Expected header: $RELEASE_VERSION  $date"
              echo "Found header:    $header"
              exit 1
          else
              echo "Changes.md heading looks good."
          fi
      - name: Release Notes Capture
        run: |
          sed -n '/^[0-9]/,/^[0-9]/p' Changes.md | head -n-1 | tail -n-1 > release-notes.md
          echo "Release Notes Will be..."
          echo "========================"
          cat release-notes.md
